### ISSUE TITLE
Add a docker file

### ISSUE THREAD

**Issue by edurenye** [Quedale/OnvifDeviceManager#9]
Create a docker file to make the installation more easier

**Comment by edurenye** [comment]
I thought it was a web UI, sorry.

Well, would be nice to have a web UI

**Comment by Quedale** [comment]
Related to Issue #10, I'm reopening this issue for tracking.

**Comment by Quedale** [comment]
Last night I published the PoC Dockerfile.

Unfortunately, I was unable to get the microphone to work since my system uses Pulseaudio.
This isn't my recommended solution, but should provide some guidance if anyone wish to use it.

simply run [docker/docker_build_run.sh](https://github.com/Quedale/OnvifDeviceManager/blob/main/docker/docker_build_run.sh)

Let me know how that goes!

**Comment by edurenye** [comment]
The script fails for me on the build, but running manually works, maybe there is a way to move the `xhost +Local:*` into a docker compose file, would make the instructions more simple and remove the need for that script, or what do you think?
From https://gursimarsm.medium.com/run-gui-applications-in-a-docker-container-ca625bad4638
says should just be:
```
version: "3"
services:
  onvifmgr:
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
```

Why do you need the speaker device mapped?
